### ISSUE TITLE
Lib throws an exception if you try to do some actions when disconnected

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-ios#635] opened 2017-09-13 19:14 UTC
Customer [complaining](https://app.intercom.io/a/apps/ua39m1ld/respond/inbox/all/conversations/11770246159) that lib is throwing an exception sometimes. Exception seems to be one triggered by doing an operation in disconnected or failed state: `[ARTException raise:@"realtime cannot perform action in disconnected or failed state" format:@"state: %d", (int)self.realtime.connection.state_nosync];`.

I'm not an iOS dev, and some languages do use exceptions to notify failure if idiomatic (e.g. the ruby REST client). But the swift/obj-c docs don't mention throwing an exception, they say failure to (e.g.) publish the message results in callback being called with an err -- which is AFAICT what happens for most failure reasons. So not sure why this error condition results in an exception.

(Also, shouldn't `suspended` be in there?)

**Comment by jeraldAR** [comment] 2017-09-13 20:47
To help out, heres what we got from Crashlytics.

`# Crashlytics - plaintext stacktrace downloaded by Jerald Freeman at Wed, 13 Sep 2017 20:44:02 GMT
# URL: https://fabric.io/analogrepublic2/ios/apps/com.ar.freestate/issues/59b87becbe077a4dcc885bf0/sessions/latest?build=64101707
# Organization: Analog Republic
# Platform: ios
# Application: Freestate
# Version: 1.0 (49)
# Bundle Identifier: com.ar.Freestate
# Issue #: 3
# Issue ID: 59b87becbe077a4dcc885bf0
# Session ID: c65e0ece8e024e54923727f260c6af5d_133c72bc98c411e7852c56847afe9799_0_v2
# Date: 2017-09-13T20:12:00Z
# OS Version: 10.3.3 (14G60)
# Device: iPhone 6
# RAM Free: 1.9%
# Disk Free: 10.5%

#16. Crashed: com.twitter.crashlytics.ios.exception
0  Freestate                      0x1001b2578 CLSProcessRecordAllThreads + 4297008504
1  Freestate                      0x1001b2578 CLSProcessRecordAllThreads + 4297008504
2  Freestate                      0x1001b2434 CLSProcessRecordAllThreads + 4297008180
3  Freestate                      0x1001a2550 CLSHandler + 4296942928
4  Freestate                      0x1001b0580 __CLSExceptionRecord_block_invoke + 4297000320
5  libdispatch.dylib              0x1856869a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x185693ee0 _dispatch_barrier_sync_f_invoke + 84
7  Freestate                      0x1001b0014 CLSExceptionRecord + 4296998932
8  Freestate                      0x1001afe3c CLSExceptionRecordNSException + 4296998460
9  Freestate                      0x1001afa50 CLSTerminateHandler() + 4296997456
10 libc++abi.dylib                0x18521f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18521f1a8 __cxa_rethrow + 144
12 libobjc.A.dylib                0x1852306f8 objc_exception_rethrow + 44
13 Ably                           0x100a29ce8 __36-[ARTRealtimePresence get:callback:]_block_invoke.29 + 556
14 libdispatch.dylib              0x1856869e0 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x1856869a0 _dispatch_client_callout + 16
16 libdispatch.dylib              0x185694ad4 _dispatch_queue_serial_drain + 928
17 libdispatch.dylib              0x18568a2cc _dispatch_queue_invoke + 884
18 libdispatch.dylib              0x185694fa8 _dispatch_queue_override_invoke + 344
19 libdispatch.dylib              0x185696a50 _dispatch_root_queue_drain + 540
20 libdispatch.dylib              0x1856967d0 _dispatch_worker_thread3 + 124
21 libsystem_pthread.dylib        0x18588f100 _pthread_wqthread + 1096
22 libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

--

Fatal Exception: realtime cannot perform action in disconnected or failed state
0  CoreFoundation                 0x1867cefe0 __exceptionPreprocess
1  libobjc.A.dylib                0x185230538 objc_exception_throw
2  CoreFoundation                 0x1867cef28 -[NSException initWithCoder:]
3  Ably                           0x100a1e000 (Missing)
4  Ably                           0x100a29b60 (Missing)
5  libdispatch.dylib              0x1856869e0 _dispatch_call_block_and_release
6  libdispatch.dylib              0x1856869a0 _dispatch_client_callout
7  libdispatch.dylib              0x185694ad4 _dispatch_queue_serial_drain
8  libdispatch.dylib              0x18568a2cc _dispatch_queue_invoke
9  libdispatch.dylib              0x185694fa8 _dispatch_queue_override_invoke
10 libdispatch.dylib              0x185696a50 _dispatch_root_queue_drain
11 libdispatch.dylib              0x1856967d0 _dispatch_worker_thread3
12 libsystem_pthread.dylib        0x18588f100 _pthread_wqthread
13 libsystem_pthread.dylib        0x18588ecac start_wqthread

#0. com.apple.main-thread
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  GraphicsServices               0x188115074 GSEventRunModal + 100
6  UIKit                          0x18c965c9c UIApplicationMain + 208
7  Freestate                      0x10009f498 main (AppDelegate.swift:21)
8  libdyld.dylib                  0x1856b959c start + 4

#1. com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1871c5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  Foundation                     0x1871e6b84 -[NSRunLoop(NSRunLoop) runUntilDate:] + 96
7  UIKit                          0x18d2ef830 -[UIEventFetcher threadMain] + 136
8  Foundation                     0x1872c3318 __NSThread__start__ + 996
9  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
10 libsystem_pthread.dylib        0x18589159c _pthread_body + 282
11 libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#2. com.twitter.crashlytics.ios.MachExceptionServer
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  Freestate                      0x10019d420 CLSMachExceptionServer + 4296922144
3  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
4  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
5  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#3. com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  CFNetwork                      0x186eb7df4 +[NSURLConnection(Loader) _resourceLoadLoop:] + 404
6  Foundation                     0x1872c3318 __NSThread__start__ + 996
7  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
8  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
9  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#4. com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  CoreFoundation                 0x1866f79c0 CFRunLoopRun + 112
6  CoreMotion                     0x18d803fdc (null) + 203104
7  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
8  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
9  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#5. Thread
0  libsystem_kernel.dylib         0x1857c9314 __semwait_signal + 8
1  libsystem_c.dylib              0x1856e88b0 nanosleep + 212
2  libsystem_c.dylib              0x185751270 sleep + 44
3  KSCrashAblyFork                0x100c0bbc0 monitorCachedData + 612
4  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
5  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
6  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#6. KSCrash Exception Handler (Secondary)
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  libsystem_kernel.dylib         0x1857af33c thread_suspend + 80
3  KSCrashAblyFork                0x100c133a0 handleExceptions + 124
4  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
5  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
6  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#7. KSCrash Exception Handler (Primary)
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  KSCrashAblyFork                0x100c133cc handleExceptions + 168
3  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
4  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
5  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#8. com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  Foundation                     0x1871c5db4 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 304
6  SocketRocket                   0x100f9edf8 -[_SRRunLoopThread main] + 252
7  Foundation                     0x1872c3318 __NSThread__start__ + 996
8  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
9  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
10 libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#9. com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x1857c923c __select + 8
1  CoreFoundation                 0x186783cb0 __CFSocketManager + 632
2  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
3  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
4  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#10. Thread
0  libsystem_kernel.dylib         0x1857c8e1c __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x185890814 _pthread_cond_wait + 640
2  libc++.1.dylib                 0x1851b9ac8 std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 56
3  JavaScriptCore                 0x18b05ef08 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 112
4  JavaScriptCore                 0x18b05ee7c bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>::threadRunLoop() + 168
5  JavaScriptCore                 0x18b05ed5c std::__1::__shared_ptr_emplace<std::__1::mutex, std::__1::allocator<std::__1::mutex> >::~__shared_ptr_emplace() + 34
6  JavaScriptCore                 0x18b05f00c void* std::__1::__thread_proxy<std::__1::tuple<void (*)(bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*), bmalloc::AsyncTask<bmalloc::Heap, void (bmalloc::Heap::*)()>*> >(void*) + 92
7  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
8  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
9  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#11. WebThread
0  libsystem_kernel.dylib         0x1857ab224 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1857ab09c mach_msg + 72
2  CoreFoundation                 0x18677ce90 __CFRunLoopServiceMachPort + 192
3  CoreFoundation                 0x18677aae4 __CFRunLoopRun + 1060
4  CoreFoundation                 0x1866aada4 CFRunLoopRunSpecific + 424
5  WebCore                        0x18b37cd3c RunWebThread(void*) + 456
6  libsystem_pthread.dylib        0x18589168c _pthread_body + 240
7  libsystem_pthread.dylib        0x18589159c _pthread_body + 282
8  libsystem_pthread.dylib        0x18588ecb4 thread_start + 4

#12. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588f1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#13. com.apple.root.background-qos
0  libsystem_kernel.dylib         0x1857c98e8 __ulock_wait + 8
1  libdispatch.dylib              0x18569977c _dispatch_ulock_wait + 48
2  libdispatch.dylib              0x1856998a4 _dispatch_thread_event_wait_slow + 36
3  libdispatch.dylib              0x1856974f0 _dispatch_barrier_sync_f_slow + 236
4  Ably                           0x100a004e0 -[ARTPublicEventEmitter off] + 92
5  Ably                           0x100a202d4 -[ARTRealtimeChannel off] + 128
6  Freestate                      0x10018f874 AppDelegate.(disconnectChannel(identifier : String, channel : ARTRealtimeChannel?) -> ()).(closure #1) (AppDelegate.swift:64)
7  libdispatch.dylib              0x1856869e0 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x1856869a0 _dispatch_client_callout + 16
9  libdispatch.dylib              0x185696bac _dispatch_root_queue_drain + 888
10 libdispatch.dylib              0x1856967d0 _dispatch_worker_thread3 + 124
11 libsystem_pthread.dylib        0x18588f100 _pthread_wqthread + 1096
12 libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#14. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588f1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#15. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588f1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#16. Crashed: com.twitter.crashlytics.ios.exception
0  Freestate                      0x1001b2578 CLSProcessRecordAllThreads + 4297008504
1  Freestate                      0x1001b2578 CLSProcessRecordAllThreads + 4297008504
2  Freestate                      0x1001b2434 CLSProcessRecordAllThreads + 4297008180
3  Freestate                      0x1001a2550 CLSHandler + 4296942928
4  Freestate                      0x1001b0580 __CLSExceptionRecord_block_invoke + 4297000320
5  libdispatch.dylib              0x1856869a0 _dispatch_client_callout + 16
6  libdispatch.dylib              0x185693ee0 _dispatch_barrier_sync_f_invoke + 84
7  Freestate                      0x1001b0014 CLSExceptionRecord + 4296998932
8  Freestate                      0x1001afe3c CLSExceptionRecordNSException + 4296998460
9  Freestate                      0x1001afa50 CLSTerminateHandler() + 4296997456
10 libc++abi.dylib                0x18521f5d4 std::__terminate(void (*)()) + 16
11 libc++abi.dylib                0x18521f1a8 __cxa_rethrow + 144
12 libobjc.A.dylib                0x1852306f8 objc_exception_rethrow + 44
13 Ably                           0x100a29ce8 __36-[ARTRealtimePresence get:callback:]_block_invoke.29 + 556
14 libdispatch.dylib              0x1856869e0 _dispatch_call_block_and_release + 24
15 libdispatch.dylib              0x1856869a0 _dispatch_client_callout + 16
16 libdispatch.dylib              0x185694ad4 _dispatch_queue_serial_drain + 928
17 libdispatch.dylib              0x18568a2cc _dispatch_queue_invoke + 884
18 libdispatch.dylib              0x185694fa8 _dispatch_queue_override_invoke + 344
19 libdispatch.dylib              0x185696a50 _dispatch_root_queue_drain + 540
20 libdispatch.dylib              0x1856967d0 _dispatch_worker_thread3 + 124
21 libsystem_pthread.dylib        0x18588f100 _pthread_wqthread + 1096
22 libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#17. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588f1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#18. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588efd0 _pthread_wqthread + 792
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

#19. Thread
0  libsystem_kernel.dylib         0x1857c9a88 __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x18588f1a4 _pthread_wqthread + 1260
2  libsystem_pthread.dylib        0x18588ecac start_wqthread + 4

`

**Comment by tcard** [comment] 2017-09-13 21:16
This is a duplicate of #630.

**Closed by tcard** 2017-09-13 21:16 UTC

**Comment by jeraldAR** [comment] 2017-09-13 21:20
@tcard ,

So is there a fix for this? Not sure why our ticket was closed when the duplicate doesn't really say what to do. Please let us know! Gracias!

**Comment by tcard** [comment] 2017-09-13 21:23
@jeraldAR Sorry, there's no fix yet (the other ticket would be closed if there was) but expect one very soon. I'll try my best to have it tomorrow. Gracias a ti por el reporte :)

**Comment by jeraldAR** [comment] 2017-09-13 21:25
@tcard, Gracias hermano. Keep us posted. Looking forward to the fix.

**Comment by tcard** [comment] 2017-09-14 17:16
@jeraldAR This is fixed now in #636. It still needs to be reviewed, merged and released, which will happen soonish.

**Comment by tcard** [comment] 2017-09-15 11:38
@jeraldAR I just released 1.0.9 with this fix.

**Comment by jeraldAR** [comment] 2017-09-15 17:13
@tcard,

Thank you so much. Im going to give it a try. Will let you know if everything is good 👍

**Comment by shoaibahmedqureshi** [comment] 2018-01-25 16:34
@tcard Is it merged yet into master?  as I am also experiencing this crash issue and I am using this specific commit pod 'Ably', :git => 'https://github.com/ably/ably-ios.git', :commit => 'f5fc0531912049bdadecc451b3b8429290880cf3' as it is not merged either . Any idea how can I have both of these fixes together even if they are not merged yet ?

**Comment by funkyboy** [comment] 2018-01-25 17:49
@shoaibahmedqureshi that commit has been merged into master and is part of 1.0.10

**Comment by shoaibahmedqureshi** [comment] 2018-01-25 19:40
@funkyboy thanks alot for your response . please also mention if this particular issue #635 is also a part of it 1.0.10 ?

**Comment by funkyboy** [comment] 2018-01-25 22:15
@shoaibahmedqureshi Yes, also this (and related fix) is included in 1.0.10
